
 /* ---- Colors.h --------------------------------------------------------- */
 /* This header file contains color definitions in text mode 				*/
 /* ----------------------------------------------------------------------- */

 #ifndef _COLORS_H_
 #define _COLORS_H_

 #define	BRIGHT		0x0800
 #define	FLASHING	0x8000
 #define	BLACK		0x0000
 #define	BLUE		0x0100
 #define	GREEN		0x0200
 #define	CYAN		0x0300
 #define	RED		0x0400
 #define	MAGENTA		0x0500
 #define	YELLOW		0x0600
 #define	WHITE		0x0700
 #define	BACKGROUND	* 16
 #define	FOREGROUND	* 1

 #endif